#!/usr/bin/env bash

if [[ -n "${WINWM_COMMON_SH_LOADED:-}" ]]; then
  return 0
fi
WINWM_COMMON_SH_LOADED=1

WINWM_MANAGED_BY="${WINWM_MANAGED_BY:-winwm-dotfiles}"
WINWM_DIR_MARKER=".managed-by-winwm-dotfiles"

_winwm_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WINWM_REPO_ROOT="$(cd "$_winwm_lib_dir/.." && pwd)"

repo_root() {
  printf '%s\n' "$WINWM_REPO_ROOT"
}

log() {
  printf '[winwm] %s\n' "$*"
}

warn() {
  printf '[winwm:warn] %s\n' "$*" >&2
}

die() {
  printf '[winwm:error] %s\n' "$*" >&2
  exit 1
}

need_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || die "Missing required command: $cmd"
}

has_arg() {
  local needle="$1"
  shift

  local arg
  for arg in "$@"; do
    [[ "$arg" == "$needle" ]] && return 0
  done

  return 1
}

timestamp_utc() {
  date -u '+%Y-%m-%dT%H:%M:%SZ'
}

timestamp_file() {
  date -u '+%Y%m%dT%H%M%SZ'
}

versions_file() {
  printf '%s\n' "$(repo_root)/versions.lock"
}

state_dir() {
  printf '%s\n' "$(repo_root)/state"
}

cache_dir() {
  printf '%s\n' "$(repo_root)/cache"
}

paths_env_file() {
  printf '%s\n' "$(state_dir)/paths.env"
}

manifest_file() {
  printf '%s\n' "$(state_dir)/manifest.tsv"
}

load_versions() {
  local file
  file="$(versions_file)"

  [[ -f "$file" ]] || die "Missing versions lock file: $file"
  # shellcheck source=/dev/null
  source "$file"

  [[ -n "${GLAZEWM_VERSION:-}" ]] || die "versions.lock did not set GLAZEWM_VERSION"
  [[ -n "${ZEBAR_VERSION:-}" ]] || die "versions.lock did not set ZEBAR_VERSION"

  export GLAZEWM_VERSION ZEBAR_VERSION
}

load_state_if_exists() {
  local file
  file="$(paths_env_file)"

  if [[ -f "$file" ]]; then
    # shellcheck source=/dev/null
    source "$file"
  fi
}

shell_quote() {
  local value="${1-}"
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

write_state_env() {
  mkdir -p "$(state_dir)"

  local file tmp key
  file="$(paths_env_file)"
  tmp="$(mktemp)"

  {
    printf '# Generated by %s. Do not edit by hand.\n' "$WINWM_MANAGED_BY"
    printf '# Regenerated at %s.\n' "$(timestamp_utc)"

    local keys=(
      WINWM_MANAGED_BY
      WIN_HOME_WIN
      WIN_HOME_WSL
      WINWM_APP_ROOT_WIN
      WINWM_APP_ROOT_WSL
      GLAZEWM_VERSION
      ZEBAR_VERSION
      GLAZEWM_INSTALL_ROOT_WIN
      GLAZEWM_INSTALL_ROOT_WSL
      ZEBAR_INSTALL_ROOT_WIN
      ZEBAR_INSTALL_ROOT_WSL
      GLAZEWM_EXE_WIN
      ZEBAR_EXE_WIN
      GLAZEWM_CONFIG_WIN
      GLAZEWM_CONFIG_WSL
      GLAZEWM_LIVE_DIR_WIN
      GLAZEWM_LIVE_DIR_WSL
      ZEBAR_ROOT_WIN
      ZEBAR_ROOT_WSL
      ZEBAR_PACK_WIN
      ZEBAR_PACK_WSL
      STARTUP_SHORTCUT_WIN
      STARTUP_SHORTCUT_WSL
    )

    for key in "${keys[@]}"; do
      if [[ -v "$key" && -n "${!key}" ]]; then
        printf 'export %s=%s\n' "$key" "$(shell_quote "${!key}")"
      fi
    done
  } >"$tmp"

  mv "$tmp" "$file"
}

sha256_file() {
  local path="$1"

  if [[ -f "$path" ]]; then
    sha256sum "$path" | awk '{print $1}'
  else
    printf '%s\n' '-'
  fi
}

record_manifest() {
  local path="$1"
  local type="$2"
  local sha="${3:--}"
  local module="${4:-${WINWM_MODULE_NAME:-unknown}}"
  local file tmp

  mkdir -p "$(state_dir)"
  file="$(manifest_file)"
  tmp="$(mktemp)"

  if [[ -f "$file" ]]; then
    p="$path" awk -F '\t' '$1 != ENVIRON["p"] { print }' "$file" >"$tmp"
  fi

  printf '%s\t%s\t%s\t%s\t%s\n' \
    "$path" \
    "$type" \
    "$sha" \
    "$(timestamp_utc)" \
    "$module" >>"$tmp"

  mv "$tmp" "$file"
}

manifest_has_path() {
  local path="$1"
  local file
  file="$(manifest_file)"

  [[ -f "$file" ]] || return 1
  p="$path" awk -F '\t' '$1 == ENVIRON["p"] { found = 1 } END { exit found ? 0 : 1 }' "$file"
}

is_managed_file() {
  local path="$1"

  if [[ -d "$path" ]]; then
    [[ -f "$path/$WINWM_DIR_MARKER" ]] && return 0
    return 1
  fi

  if [[ -f "$path" ]]; then
    grep -qa "managed-by: $WINWM_MANAGED_BY" "$path" && return 0
    grep -qa "managed-by:$WINWM_MANAGED_BY" "$path" && return 0
  fi

  return 1
}

write_managed_dir_marker() {
  local dir="$1"
  mkdir -p "$dir"
  {
    printf 'managed-by: %s\n' "$WINWM_MANAGED_BY"
    printf 'created-at: %s\n' "$(timestamp_utc)"
  } >"$dir/$WINWM_DIR_MARKER"
}

backup_if_unmanaged() {
  local path="$1"

  [[ -e "$path" || -L "$path" ]] || return 0

  if is_managed_file "$path"; then
    return 0
  fi

  local backup
  backup="$path.bak.$(timestamp_file)"
  mv "$path" "$backup"
  warn "Backed up unmanaged target to $backup"
}

backup_dir_if_unmanaged() {
  local dir="$1"

  [[ -e "$dir" || -L "$dir" ]] || return 0

  if [[ ! -d "$dir" ]]; then
    backup_if_unmanaged "$dir"
    return 0
  fi

  if is_managed_file "$dir"; then
    return 0
  fi

  if find "$dir" -mindepth 1 -maxdepth 1 -print -quit | grep -q .; then
    local backup
    backup="$dir.bak.$(timestamp_file)"
    mv "$dir" "$backup"
    warn "Backed up unmanaged directory to $backup"
  fi
}

remove_managed_file() {
  local path="$1"
  local force="${2:-false}"

  [[ -e "$path" || -L "$path" ]] || return 0

  if [[ "$force" == "true" ]] || is_managed_file "$path"; then
    rm -f "$path"
    log "Removed $path"
    return 0
  fi

  warn "Refusing to remove unmanaged file: $path"
}

remove_managed_dir() {
  local dir="$1"
  local force="${2:-false}"

  [[ -e "$dir" || -L "$dir" ]] || return 0

  if [[ "$force" == "true" ]] || is_managed_file "$dir"; then
    rm -rf "$dir"
    log "Removed $dir"
    return 0
  fi

  warn "Refusing to remove unmanaged directory: $dir"
}

create_wsl_link() {
  local link="$1"
  local target="$2"

  mkdir -p "$(dirname "$link")"

  if [[ -L "$link" ]]; then
    ln -sfn "$target" "$link"
    return 0
  fi

  if [[ -e "$link" ]]; then
    warn "WSL edit link path exists and is not a symlink: $link"
    return 1
  fi

  ln -s "$target" "$link"
}

remove_wsl_link() {
  local link="$1"
  local force="${2:-false}"

  if [[ -L "$link" ]]; then
    rm -f "$link"
    log "Removed WSL edit link $link"
    return 0
  fi

  if [[ -e "$link" && "$force" == "true" ]]; then
    rm -rf "$link"
    log "Removed $link"
  elif [[ -e "$link" ]]; then
    warn "Refusing to remove non-symlink WSL path: $link"
  fi
}

run_script() {
  local script="$1"
  shift

  [[ -x "$script" ]] || die "Script is not executable: $script"
  "$script" "$@"
}
